version: '3'

services:
  devdb:
    image: postgres:alpine
    volumes: 
        - data:/var/lib/postgresql/data
  devapp:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@devdb/
    command: python3 -m flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    depends_on:
      - devdb

volumes:
  data:
