"""create and seed greetings table

Revision ID: af872fbcf31e
Revises: 
Create Date: 2018-12-07 12:33:39.481767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af872fbcf31e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    greetings = op.create_table('greeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.bulk_insert(greetings,
        [{'id': 1, 'text': 'Hello from database!'}])

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('greeting')
    # ### end Alembic commands ###
