openapi: "3.0.0"
info:
  version: "1.0.0"
  title: Url Shortener
paths:
  /shorten:
    post:
      summary: Create a new shorturl
      operationId: api.shorturl.create
      tags:
        - Shorturl
      requestBody:
        description: Shorturl to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Shorturl'
      responses:
        '201':
          description: Successfully created shorturl
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShortcodeJSON"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /{shortcode}:
    parameters:
      - in: path
        name: shortcode
        schema:
          $ref: "#/components/schemas/shortcode"
        required: true
    get:
      summary: Get redirected with a shortcode
      operationId: api.shorturl.redirect
      tags:
        - Shorturl
      responses:
        '302':
          description: Redirect to the full URL associated with this shortcode
        default:
          description: shortcode not found or other error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /{shortcode}/stats:
    parameters:
      - in: path
        name: shortcode
        schema:
          $ref: "#/components/schemas/shortcode"
        required: true
    get:
      summary: Get statistics for a shortcode
      operationId: api.shorturl.stats
      tags:
        - Shorturl
      responses:
        '200':
          description: Statistics for the shortcode
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ShorturlStats"
        default:
          description: shortcode not found or other error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    shortcode:
      type: string
      minLength: 6
      maxLength: 6
      pattern: "^[a-zA-Z0-9_]*$"
    Shorturl:
      required:
        - url
      properties:
        url:
          type: string
          format: uri
        shortcode:
          $ref: "#/components/schemas/shortcode"
      example:
        url: 'http://www.example.com'
        shortcode: 'qwerty'
    ShorturlStats:
      required:
        - created
        - lastRedirect
        - redirectCount
      properties:
        created:
          type: string
          format: date-time
        lastRedirect:
          type: string
          format: date-time
        redirectCount:
          type: integer
          format: int32
    ShortcodeJSON:
      required:
        - shortcode
      properties:
        shortcode:
          $ref: "#/components/schemas/shortcode"
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
